### ISSUE TITLE
How to use in NodeJS

### ISSUE THREAD

**Issue by haraldjordan78** [m-rots/mediainfo#1]
Thanks for this, its a great idea. 
Assumed i don't want to use typescript, is there a way to still use this?

**Comment by m-rots** [comment]
Great first issue!

This library is fully usable from NodeJS as well!
Without TypeScript this would be the code required to run this library:

```js
const mediainfo = require('node-mediainfo');

async function main() {
  const result = await mediainfo.default('your path');
  console.log(result);
}

main();
```

I hope this enables you to use this library! :)

**Comment by m-rots** [comment]
I've just released a small update to this package, which enables you to import the module without the `.default`.

The Readme has also been updated with both NodeJS and ES6 instructions.
```js
// Using ES6 imports
import mediainfo from 'node-mediainfo';

// Using Node.js `require()`
const mediainfo = require('node-mediainfo');

async function main() {
  const result = await mediainfo('path to media file');
  console.log(result);
}

main();
```

Cheers!
