### ISSUE TITLE
Advanced output

### ISSUE THREAD

**Issue by emcodem** [m-rots/mediainfo#3]
Hey :-) I had some play but didnt get it to work: is there any chance to get the "Advanced" output (-f on mediainfo commandline)?

**Comment by m-rots** [comment]
Heyo! Sorry for the very, very late response, university is getting tooo much haha. The advanced output is the default output. Pretty much this WASM implementation runs as the following CLI command: `mediainfo <path> --Output=JSON --Full`.

I've also updated the library today to the latest version, and I've added an example!
Let me know whether you need extra help getting this library to work! :)
